baseURL = 'https://photo.too-many-machines.com/'
languageCode = 'en'
title = 'Photo'
theme = 'gallery'
copyright = "© Igor Wawrzyniak"
disableKinds = ["taxonomy", "term"]
defaultContentLanguage = "en"
enableRobotsTXT = true
timeZone = "Europe/London"


[params]
  title = "Photo"
  defaultTheme = "dark"

[author]
  name = "Igor Wawrzyniak"

[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.112.0"

[menu]
[[menu.footer]]
  name = 'Photo'
  url = '/'
  weight = 10
[[menu.footer]]
  name = 'Too Many Machines'
  url = 'https://too-many-machines.com/'
  weight = 1
[[menu.footer]]
  name = 'Advent of Code'
  url = 'https://advent.too-many-machines.com/'
  weight = 20
[[menu.footer]]
  name = 'Selfhosting'
  url = 'https://selfhosting.too-many-machines.com/'
  weight = 30
[[menu.main]]
  name = 'Too Many Machines'
  url = 'https://too-many-machines.com/'
  weight = 100